language: objective-c
before_install:
- brew install xctool
- pod install --project-directory=Example

script:
- xctool -workspace Example/TLInputsChainHelper.xcworkspace -scheme TLInputsChainHelper-Example test -sdk iphonesimulator  ONLY_ACTIVE_ARCH=NO
- pod lib lint --quick
